name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster1    # TODO: update to cluster name
  GKE_ZONE: us-central1
  GOOGLE_APPLICATION_CREDENTIAL: ${{ secrets.SA_KEY }}
  

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v3
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'
  #       cache: maven
  #   - name: Build Currency Exchange Microservice
  #     run: mvn -B package --file ./01-currency-exchange-microservice-basic/pom.xml
  #   - name: Build Currency Conversion Microservice
  #     run: mvn -B package --file ./02-currency-conversion-microservice-basic/pom.xml

  # Docker_Deploy_conversion:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build currency conversion service Docker image
  #     run: docker build -t sharmanayan/currency-conversion:0.0.1-RELEASE ./01-currency-exchange-microservice-basic

  #   - name: Login to Docker registry
  #     run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u sharmanayan --password-stdin

  #   - name: Push currency conversion service Docker image to registry
  #     run: docker push sharmanayan/currency-conversion:0.0.1-RELEASE

  # Docker_Deploy_Exchange:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build exchange service Docker image
  #     run: docker build -t sharmanayan/currency-exchange:0.0.1-RELEASE ./02-currency-conversion-microservice-basic

  #   - name: Login to Docker registry
  #     run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u sharmanayan --password-stdin

  #   - name: Push exchange service Docker image to registry
  #     run: docker push sharmanayan/currency-exchange:0.0.1-RELEASE

  deploy:
    # needs: Docker_Deploy_Exchange
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure Google Cloud credentials
      uses: google-github-actions/setup-gcloud@v1

    - name: Authenticate gcloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.SA_KEY }}

    - name: Initialize Terraform for Currency Exchange service
      run: terraform init -chdir ./01-currency-exchange-microservice-basic/Configuration
        
    - name: Initialize Terraform for Currency Conversion service
      run: terraform init -chdir ./02-currency-conversion-microservice-basic/Configuration

    - name: Debug Credentials
      run: |
        echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
        gcloud auth list

    - name: Terraform Plan for Currency Exchange service
      run: terraform plan -chdir ./01-currency-exchange-microservice-basic/Configuration

    - name: Terraform Plan for Currency Conversion service
      run: terraform plan -chdir ./02-currency-conversion-microservice-basic/Configuration

    - name: Terraform Apply for Currency Exchange service
      run: terraform apply -auto-approve -chdir ./01-currency-exchange-microservice-basic/Configuration

    - name: Terraform Apply for Currency Conversion service
      run: terraform apply -auto-approve -chdir ./02-currency-conversion-microservice-basic/Configuration
        